# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemos" do
  name "mnemos"
  desc "Persistent memory engine for AI agents"
  homepage "https://github.com/s60yucca/mnemos"
  version "1.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnemos"

  on_macos do
    on_intel do
      url "https://github.com/s60yucca/mnemos/releases/download/v#{version}/mnemos_darwin_amd64.tar.gz"
      sha256 "7d1c6b166eff43e3aaf5ac3f101e8ae7cf1e12a0b49c7d215b1ebeabb5ba807f"
    end
    on_arm do
      url "https://github.com/s60yucca/mnemos/releases/download/v#{version}/mnemos_darwin_arm64.tar.gz"
      sha256 "3ad93978c04ebc16aff9d5ec120274b83c7885eda6c9501a82310f5cfed7c9fa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/s60yucca/mnemos/releases/download/v#{version}/mnemos_linux_amd64.tar.gz"
      sha256 "fb4677c3304b1032e78a553a51bf644a642b43d26d39e2265ee0375cce70064d"
    end
    on_arm do
      url "https://github.com/s60yucca/mnemos/releases/download/v#{version}/mnemos_linux_arm64.tar.gz"
      sha256 "b3c7188b1e3706ffd25c78523dc122d3f8c6e98224fe427751d80b83792d3352"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mnemos"]
    end
  end

  # No zap stanza required
end
