# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemos" do
  name "mnemos"
  desc "Persistent memory engine for AI agents"
  homepage "https://github.com/s60yucca/mnemos"
  version "1.0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnemos"

  on_macos do
    on_intel do
      url "https://github.com/s60yucca/mnemos/releases/download/v#{version}/mnemos_darwin_amd64.tar.gz"
      sha256 "5583f004eb6c86b163f0556f811427fc9ee72fe143bb5d493bf7938a30bec30e"
    end
    on_arm do
      url "https://github.com/s60yucca/mnemos/releases/download/v#{version}/mnemos_darwin_arm64.tar.gz"
      sha256 "dfddd4c221810f738d7998699fc64efe0e8a36baab51350da75dbac69a94c765"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/s60yucca/mnemos/releases/download/v#{version}/mnemos_linux_amd64.tar.gz"
      sha256 "a28270d2324789d5634dc1a4aac523afc0eafd0ed990748dfe5a95cef25284a1"
    end
    on_arm do
      url "https://github.com/s60yucca/mnemos/releases/download/v#{version}/mnemos_linux_arm64.tar.gz"
      sha256 "cd39ae9d608693fcc9d56e5f556fd78c4d574157c2e54f2b39bc3cdd34bcc775"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mnemos"]
    end
  end

  # No zap stanza required
end
