# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemos" do
  name "mnemos"
  desc "Persistent memory engine for AI agents"
  homepage "https://github.com/s60yucca/mnemos"
  version "1.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnemos"

  on_macos do
    on_intel do
      url "https://github.com/s60yucca/mnemos/releases/download/v#{version}/mnemos_darwin_amd64.tar.gz"
      sha256 "bdcebe6dda4b151818cb4932ebd4f31af82887b5d4d8d7aaea36087f58cf2477"
    end
    on_arm do
      url "https://github.com/s60yucca/mnemos/releases/download/v#{version}/mnemos_darwin_arm64.tar.gz"
      sha256 "3b5621d5d97f3842c0dd7080ddd0c286858acb24d06adca213c1c82bc96c05ff"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/s60yucca/mnemos/releases/download/v#{version}/mnemos_linux_amd64.tar.gz"
      sha256 "6a5b7782f3767092dcc6e0cf06c9ad0609868cbd1dc913f76f0e9c06ff027c62"
    end
    on_arm do
      url "https://github.com/s60yucca/mnemos/releases/download/v#{version}/mnemos_linux_arm64.tar.gz"
      sha256 "98227ac12d727e3472f9fa3a57e58c7a50f146f9627b828754dcb5146fb48f47"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mnemos"]
    end
  end

  # No zap stanza required
end
