# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemos < Formula
  desc "Persistent memory engine for AI agents"
  homepage "https://github.com/s60yucca/mnemos"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/s60yucca/mnemos/releases/download/v1.0.3/mnemos_darwin_amd64.tar.gz"
      sha256 "a85f120478c8ffc97c0f7d1b24df1a08cbd4fdcb93158d4da8907be75e743805"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/s60yucca/mnemos/releases/download/v1.0.3/mnemos_darwin_arm64.tar.gz"
      sha256 "9da8d1f090f178f1094d629bf17059c42bd4a73a508418b5b2ff7fcb4d0fe34d"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/s60yucca/mnemos/releases/download/v1.0.3/mnemos_linux_amd64.tar.gz"
      sha256 "19a68ff3a014b1b01148a4e34437546deed3937dd33878c39808b0b1bc78cde4"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/s60yucca/mnemos/releases/download/v1.0.3/mnemos_linux_arm64.tar.gz"
      sha256 "af79ed54513bb8fddfa664dc4d40336797fc3086de283183e200eafb9e3c2981"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  test do
    system "#{bin}/mnemos", "version"
  end
end
