# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemos < Formula
  desc "Persistent memory engine for AI agents"
  homepage "https://github.com/s60yucca/mnemos"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/s60yucca/mnemos/releases/download/v1.0.4/mnemos_darwin_amd64.tar.gz"
      sha256 "200bdb576c9701500d3f4d3d5e176a3febc3b47fac683e2a96d65228e6475d72"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/s60yucca/mnemos/releases/download/v1.0.4/mnemos_darwin_arm64.tar.gz"
      sha256 "4e72166782af5515e7e66909a10595f214e31c4bc50706acd79019b9a37bc4b3"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/s60yucca/mnemos/releases/download/v1.0.4/mnemos_linux_amd64.tar.gz"
      sha256 "55c6d31f52976f1199e9d8bdd760213460f988740d9554fa85a2d32c68016c07"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/s60yucca/mnemos/releases/download/v1.0.4/mnemos_linux_arm64.tar.gz"
      sha256 "d6cd3f518873c4ce458eed0c7e1ea8e082cb3dd61822becca07484fb1dbf4b6a"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  test do
    system "#{bin}/mnemos", "version"
  end
end
