# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemos < Formula
  desc "Persistent memory engine for AI agents"
  homepage "https://github.com/s60yucca/mnemos"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/s60yucca/mnemos/releases/download/v1.0.1/mnemos_darwin_amd64.tar.gz"
      sha256 "441973d6b382960ee8fbd0b3ced890f20048b0690e3672d2c145a9bf52691889"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/s60yucca/mnemos/releases/download/v1.0.1/mnemos_darwin_arm64.tar.gz"
      sha256 "8cf8f23d0e6501d95b99406eb4df0036e35c27b625bd2500c3c2d8b33d238c81"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/s60yucca/mnemos/releases/download/v1.0.1/mnemos_linux_amd64.tar.gz"
      sha256 "750a7b83cb4937fa402d2f82fcffdcb4078c2d143ba082fa34d564d07f34cafd"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/s60yucca/mnemos/releases/download/v1.0.1/mnemos_linux_arm64.tar.gz"
      sha256 "1102fa3b4717da7661501b1a198d842ccab59639d22ed3cf9fc5d546ad6c5922"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  test do
    system "#{bin}/mnemos", "version"
  end
end
